name: Push tag

on:
  push:
    tags:
      - '*'

jobs:
  push-tag:
    name: Tag image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - registry: pbotapps
            repository: federation/service/pudl
          - registry: pbotapps
            repository: federation/app/pudl
    steps:
      - uses: actions/checkout@v3
      - name: Pull
        uses: ./packages/actions/pull
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
          registry: ${{ matrix.registry }}
          repository: ${{ matrix.repository }}
          tag: ${{ github.sha }}
      - name: Push
        uses: ./packages/actions/push
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
          registry: ${{ matrix.registry }}
          repository: ${{ matrix.repository }}
          tag: ${{ github.ref_name }}
