name: Push tag

on:
  push:
    tags:
      - '*'

jobs:
  create-apps:
    name: Rebuild apps
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - app: bus-reservation
            directory: apps/bus-reservation
            registry: pbotapps
            repository: federation/app/bus-reservation
            files: |
              packages/components/.env.production.local:
                - VITE_GRAPHQL_URL=https://pbotapps.portland.gov/graphql/reservation
          - app: pudl
            directory: apps/pudl
            registry: pbotapps
            repository: federation/app/pudl
            files: |
              packages/components/.env.production.local:
                - VITE_GRAPHQL_URL=https://pudl.portland.gov/graphql
          - app: sign-library
            directory: apps/sign-library
            registry: pbotapps
            repository: federation/app/sign-library
            files: |
              packages/components/.env.production.local:
                - VITE_GRAPHQL_URL=https://pbotapps.portland.gov/graphql/sign
          - app: support
            directory: apps/support
            registry: pbotapps
            repository: federation/app/support
            files: |
              packages/components/.env.production.local:
                - VITE_GRAPHQL_URL=https://pbotapps.portland.gov/graphql/support
    steps:
      - uses: actions/checkout@v3
      - uses: ./packages/actions/file-writer
        if: matrix.files
        name: Create files
        with:
          input: |
            packages/components/.env.local:
              - VITE_AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}
              - VITE_AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}
      - uses: ./packages/actions/file-writer
        if: matrix.files
        name: Create files
        with:
          input: ${{ matrix.files }}
      - name: Build
        uses: ./packages/actions/build
        with:
          dockerfile: ./.docker/apps/Dockerfile
          artifact-name: ${{ matrix.app }}-image
          directory: ${{ matrix.directory }}
      - name: Push
        uses: ./packages/actions/push
        with:
          credentials: ${{ secrets. AZURE_CREDENTIALS }}
          registry: ${{ matrix.registry }}
          repository: ${{ matrix.repository }}
          tag: ${{ github.ref_name }}

  tag-services:
    name: Tag service images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - registry: pbotapps
            repository: federation/service/pudl
          - registry: pbotapps
            repository: federation/service/reservation
          - registry: pbotapps
            repository: federation/service/sign
          - registry: pbotapps
            repository: federation/service/support
    steps:
      - uses: actions/checkout@v3
      - name: Pull
        uses: ./packages/actions/pull
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
          registry: ${{ matrix.registry }}
          repository: ${{ matrix.repository }}
          tag: ${{ github.sha }}
      - name: Tag as SHA
        shell: bash
        run: |
          docker tag \
          ${{ format('{0}.azurecr.io', matrix.registry) }}/${{ matrix.repository }}:${{ github.sha }} \
          ${{ github.sha }}
      - name: Push
        uses: ./packages/actions/push
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
          registry: ${{ matrix.registry }}
          repository: ${{ matrix.repository }}
          tag: ${{ github.ref_name }}
