name: Deploy to staging

on:
  push:
    branches:
      - main

concurrency:
  group: staging
  cancel-in-progress: true

jobs:
  create-image:
    name: Create images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - app: pudl
            directory: apps/pudl
            registry: pbotapps
            repository: federation/app/pudl
            files: |
              packages/common/.env:
                - VITE_GRAPHQL_URL=https://pudl-test.portland.gov/graphql
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
      - name: Get pnpm store directory
        id: pnpm-store
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-store.outputs.pnpm_cache_dir }}
          key: v1-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            v1-pnpm-store-
      - uses: ./packages/actions/file-writer
        if: matrix.files
        name: Create files
        with:
          input: ${{ matrix.files }}
      - name: Build
        uses: ./packages/actions/build
        with:
          artifact-name: ${{ matrix.app }}-image
          directory: ${{ matrix.directory }}
      - name: Push
        uses: ./packages/actions/push
        with:
          credentials: ${{ secrets. AZURE_CREDENTIALS }}
          registry: ${{ matrix.registry }}
          repository: ${{ matrix.repository }}
          tag: ${{ github.sha }}

  deploy-staging:
    name: Deploy to staging
    strategy:
      fail-fast: true
      matrix:
        include:
          - app: pudl
            directory: apps/pudl
            repository: federation/app/pudl
            cluster-name: pudl-kube-data-1
            cluster-rg: pudl-kube-rg
            cluster-ns: pudl-test
            values: |
              ingress:
                annotations:
                  nginx.ingress.kubernetes.io/server-snippet: |-
                    add_header X-Robots-Tag "noindex, nofollow";
                hosts:
                  - host: pudl-test.portland.gov
                    paths:
                      - path: /
                        pathType: Prefix
                tls:
                  - secretName: pudl-test-portland-gov-tls
                    hosts:
                      - pudl-test.portland.gov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create values file
        uses: ./packages/actions/merge-values
        with:
          input: chart/values.yaml
          output: values.yaml
          values: ${{ matrix.values }}
      - name: Modify values file
        uses: ./packages/actions/merge-values
        with:
          input: values.yaml
          output: values.yaml
          values: |
            image:
              repository: ${{ format('{0}.azurecr.io', matrix.registry || 'pbotapps') }}/${{ matrix.repository }}
              tag: ${{ github.sha }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.app }}-values
          path: values.yaml
      - name: Run deploy action
        uses: ./packages/actions/deploy
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ matrix.cluster-name }}
          cluster-rg: ${{ matrix.cluster-rg }}
          namespace: ${{ matrix.cluster-ns }}
          chart: ./chart
          release-name: federated-app-${{ matrix.app }}
          values-file: values.yaml
