name: Release services

on:
  release:
    types:
      - published

concurrency:
  group: release-services
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - service: pudl
            directory: services/pudl
            repository: federation/service/pudl
            cluster-name: pbotapps-kube-1
            cluster-rg: pbotapps-kube-rg
            cluster-ns: pudl
            values: |
              ingress:
                enabled: true
                hosts:
                  - host: pudl.portland.gov
                    paths:
                      - path: /graphql
                        pathType: Prefix
                tls:
                  - secretName: pudl-portland-gov-tls
                    hosts:
                      - pudl.portland.gov
              extraEnv:
                - name: AZURE_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: '{{ include "chart.fullname" . }}'
                      key: AZURE_CLIENT_ID
                - name: AZURE_TENANT_ID
                  valueFrom:
                    secretKeyRef:
                      name: '{{ include "chart.fullname" . }}'
                      key: AZURE_TENANT_ID
                - name: AZURE_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: '{{ include "chart.fullname" . }}'
                      key: AZURE_CLIENT_SECRET
                - name: PUDL_POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: pudl-metastore
                      key: POSTGRES_PASSWORD
                - name: PUDL_POSTGRES_HOST
                  value: pudl-postgres
                - name: PUDL_POSTGRES_PORT
                  value: "5432"
                - name: PUDL_POSTGRES_USERNAME
                  value: hive_admin
    steps:
      - uses: actions/checkout@v3
      - name: Create azure secrets
        uses: ./packages/actions/file-writer
        with:
          input: |
            chart/.secret/AZURE_TENANT_ID:
              - ${{ secrets.AZURE_TENANT_ID }}
            chart/.secret/AZURE_CLIENT_ID:
              - ${{ secrets.AZURE_CLIENT_ID }}
            chart/.secret/AZURE_CLIENT_SECRET:
              - ${{ secrets.AZURE_CLIENT_SECRET }}
      - name: Create values file
        uses: ./packages/actions/merge-values
        with:
          input: chart/values.yaml
          output: values.yaml
          values: ${{ matrix.values }}
      - name: Modify values file
        uses: ./packages/actions/merge-values
        with:
          input: values.yaml
          output: values.yaml
          values: |
            fullNameOverride: ${{ matrix.service }}-service
            image:
              repository: ${{ format('{0}.azurecr.io', matrix.registry || 'pbotapps') }}/${{ matrix.repository }}
              tag: ${{ github.ref_name }}
            containerPort: 4000
            probePath: /probe
      - uses: ./packages/actions/deploy
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ matrix.cluster-name }}
          cluster-rg: ${{ matrix.cluster-rg }}
          namespace: ${{ matrix.cluster-ns }}
          chart: ./chart
          release-name: ${{ matrix.service }}-service
          values-file: values.yaml
