name: Release services

on:
  release:
    types:
      - published

concurrency:
  group: release-services
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - service: pudl
            directory: services/pudl
            repository: federation/service/pudl
            cluster-name: pbotapps-kube-1
            cluster-rg: pbotapps-kube-rg
            cluster-ns: pudl
            values: |
              ingress:
                enabled: true
                hosts:
                  - host: pudl.portland.gov
                    paths:
                      - path: /graphql
                        pathType: Prefix
                tls:
                  - secretName: pudl-portland-gov-tls
                    hosts:
                      - pudl.portland.gov
              extraEnv:
                - name: AIRFLOW_POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: pudl-airflow
                      key: POSTGRES_PASSWORD
                - name: AIRFLOW_POSTGRES_USERNAME
                  value: airflow_admin
                - name: AZURE_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: '{{ include "chart.fullname" . }}'
                      key: AZURE_CLIENT_ID
                - name: AZURE_TENANT_ID
                  valueFrom:
                    secretKeyRef:
                      name: '{{ include "chart.fullname" . }}'
                      key: AZURE_TENANT_ID
                - name: AZURE_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: '{{ include "chart.fullname" . }}'
                      key: AZURE_CLIENT_SECRET
                - name: PUDL_POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: pudl-metastore
                      key: POSTGRES_PASSWORD
                - name: PUDL_POSTGRES_HOST
                  value: pudl-postgres
                - name: PUDL_POSTGRES_PORT
                  value: "5432"
                - name: PUDL_POSTGRES_USERNAME
                  value: hive_admin
          - service: reservation
            directory: services/reservation
            repository: federation/service/reservation
            cluster-name: pbotapps-kube-1
            cluster-rg: pbotapps-kube-rg
            cluster-ns: pbotapps
            values: |
              ingress:
                enabled: true
                hosts:
                  - host: pbotapps.portland.gov
                    paths:
                      - path: /graphql/reservation
                        pathType: Prefix
                tls:
                  - secretName: pbotapps-portland-gov-tls
                    hosts:
                      - pbotapps.portland.gov
              extraEnv:
                - name: AZURE_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: '{{ include "chart.fullname" . }}'
                      key: AZURE_CLIENT_ID
                - name: AZURE_TENANT_ID
                  valueFrom:
                    secretKeyRef:
                      name: '{{ include "chart.fullname" . }}'
                      key: AZURE_TENANT_ID
                - name: AZURE_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: '{{ include "chart.fullname" . }}'
                      key: AZURE_CLIENT_SECRET
                - name: AZURE_COSMOS_URL
                  valueFrom:
                    secretKeyRef:
                      name: '{{ include "chart.fullname" . }}'
                      key: AZURE_COSMOS_URL
                - name: AZURE_COSMOS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: '{{ include "chart.fullname" . }}'
                      key: AZURE_COSMOS_KEY
          - service: sign
            directory: services/sign
            repository: federation/service/sign
            cluster-name: pbotapps-kube-1
            cluster-rg: pbotapps-kube-rg
            cluster-ns: pbotapps
            values: |
              ingress:
                enabled: true
                hosts:
                  - host: pbotapps.portland.gov
                    paths:
                      - path: /graphql/sign
                        pathType: Prefix
                tls:
                  - secretName: pbotapps-portland-gov-tls
                    hosts:
                      - pbotapps.portland.gov
              extraEnv:
                - name: AZURE_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: '{{ include "chart.fullname" . }}'
                      key: AZURE_CLIENT_ID
                - name: AZURE_TENANT_ID
                  valueFrom:
                    secretKeyRef:
                      name: '{{ include "chart.fullname" . }}'
                      key: AZURE_TENANT_ID
                - name: AZURE_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: '{{ include "chart.fullname" . }}'
                      key: AZURE_CLIENT_SECRET
                - name: AZURE_STORAGE_ACCOUNT
                  value: pbotapps
                - name: ELASTICSEARCH_HOST
                  value: https://pbotapps-es-http:9200
                - name: ELASTICSEARCH_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: pbotapps-es-elastic-user
                      key: elastic
              volumes:
                - name: elastic-cert
                  secret:
                    secretName: pbotapps-es-http-ca-internal
              volumeMounts:
                - mountPath: /home/node/services/sign/dist/elastic.crt
                  name: elastic-cert
                  subPath: tls.crt
          - service: support
            directory: services/support
            repository: federation/service/support
            cluster-name: pbotapps-kube-1
            cluster-rg: pbotapps-kube-rg
            cluster-ns: pbotapps
            values: |
              ingress:
                enabled: true
                hosts:
                  - host: pbotapps.portland.gov
                    paths:
                      - path: /graphql/support
                        pathType: Prefix
                tls:
                  - secretName: pbotapps-portland-gov-tls
                    hosts:
                      - pbotapps.portland.gov
              extraEnv:
                - name: AZURE_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: '{{ include "chart.fullname" . }}'
                      key: AZURE_CLIENT_ID
                - name: AZURE_TENANT_ID
                  valueFrom:
                    secretKeyRef:
                      name: '{{ include "chart.fullname" . }}'
                      key: AZURE_TENANT_ID
                - name: AZURE_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: '{{ include "chart.fullname" . }}'
                      key: AZURE_CLIENT_SECRET
    steps:
      - uses: actions/checkout@v3
      - name: Create azure secrets
        uses: ./packages/actions/file-writer
        with:
          input: |
            chart/.secret/AZURE_TENANT_ID:
              - ${{ secrets.AZURE_TENANT_ID }}
            chart/.secret/AZURE_CLIENT_ID:
              - ${{ secrets.AZURE_CLIENT_ID }}
            chart/.secret/AZURE_CLIENT_SECRET:
              - ${{ secrets.AZURE_CLIENT_SECRET }}
            chart/.secret/AZURE_COSMOS_URL:
              - ${{ secrets.PROD_COSMOS_URL }}
            chart/.secret/AZURE_COSMOS_KEY:
              - ${{ secrets.PROD_COSMOS_KEY }}
      - name: Create values file
        uses: ./packages/actions/merge-values
        with:
          input: chart/values.yaml
          output: values.yaml
          values: ${{ matrix.values }}
      - name: Modify values file
        uses: ./packages/actions/merge-values
        with:
          input: values.yaml
          output: values.yaml
          values: |
            fullNameOverride: ${{ matrix.service }}-service
            image:
              repository: ${{ format('{0}.azurecr.io', matrix.registry || 'pbotapps') }}/${{ matrix.repository }}
              tag: ${{ github.ref_name }}
            containerPort: 4000
            probePath: /probe
      - uses: ./packages/actions/deploy
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ matrix.cluster-name }}
          cluster-rg: ${{ matrix.cluster-rg }}
          namespace: ${{ matrix.cluster-ns }}
          chart: ./chart
          release-name: ${{ matrix.service }}-service
          values-file: values.yaml
